import { brand, escape as e } from './dom.js';
import { flag, icon } from './icons.js';
import { worlds } from '../worlds.js';
import { rounds, hint } from '../games/engine.js';

export function landingView(practice) {
  return `<section class="travel-hero"><nav class="home-nav" aria-label="On this page"><a href="#worlds">Explore the worlds</a><span aria-hidden="true">✦</span><a href="#how">How you learn</a></nav><div class="hero-brand">${brand}</div><p class="hero-slogan">Learn English. Explore the World.</p><div class="hero-practice"><h1>${e(practice.title)}</h1>${practice.unit ? `<p>${e(practice.unit)}</p>` : ''}<span>${practice.items.length} words · 4 rounds · Your own pace</span></div><button id="start" class="button primary large">Start Practice <span aria-hidden="true">→</span></button></section>
  <section id="worlds" class="world-section" aria-labelledby="world-heading"><span class="eyebrow">YOUR WORDS. A WORLD OF POSSIBILITY.</span><h2 id="world-heading" tabindex="-1">Choose Your World</h2><p>Same words. Your own adventure.</p><fieldset class="world-grid"><legend class="sr-only">Choose a world for this practice</legend>${worlds.map(w => `<label class="world-card"><input type="radio" name="world" value="${w.id}"><img src="${w.thumbnail}" alt="" width="480" height="320" loading="lazy"><span class="world-card-copy">${flag(w.flag)}<strong>${w.name}</strong><small>${w.description}</small><span class="world-choice">Explore ${e(w.place)} <span aria-hidden="true">→</span></span></span></label>`).join('')}</fieldset><button id="begin" class="button primary large" disabled>Let’s go <span aria-hidden="true">→</span></button><p id="world-status" class="small" role="status">Choose a world to begin.</p></section>
  <section id="how" class="how-section"><span class="eyebrow">A LITTLE PRACTICE. LASTING CONFIDENCE.</span><h2>How You Learn</h2><p>Step by step, make these words your own.</p><ol class="learning-cards">${rounds.map((r, i) => `<li><span class="step-dot ${r.color}">${i + 1}</span><h3>${r.name}</h3><p>${['Match English words to their meanings.', 'Find the English word for each meaning.', 'Recall the spelling with a little support.', 'Remember the word all on your own.'][i]}</p></li>`).join('')}</ol><div class="review-explainer"><span aria-hidden="true">✦</span><div><h3>Review</h3><p>A little extra practice, just for the words that need it.</p></div></div></section>`;
}

export function roundProgress(round, review = false) {
  return `<div class="round-progress"><p class="round-label">${review ? 'Review · a little extra practice' : `Round ${round + 1} of 4`}</p><ol aria-label="Round progression">${rounds.map((r, i) => `<li class="${review || i < round ? 'complete' : i === round ? 'current' : ''}" ${!review && i === round ? 'aria-current="step"' : ''}><span class="round-dot" aria-hidden="true">${review || i < round ? '✓' : i + 1}</span><span>${r.name}</span><span class="sr-only">${review || i < round ? ', completed' : i === round ? ', current round' : ', upcoming'}</span></li>`).join('')}</ol></div>`;
}

export function spellingHint(term) {
  const value = hint(term);
  return `<div class="word-hint" role="img" aria-label="Spelling hint: ${e(value.replaceAll('·', '_'))}">${value.split(/(\s+)/u).map(word => /^\s+$/u.test(word) ? '<span class="hint-space"> </span>' : `<span class="hint-word">${Array.from(word).map(c => `<span class="${c === '·' ? 'letter-slot' : 'hint-letter'}">${c === '·' ? '<span class="sr-only">_</span>' : e(c)}</span>`).join('')}</span>`).join('')}</div>`;
}

export function resultsView(practice, result) {
  const remaining = result.remaining.length;
  const title = result.accuracy === 100 ? 'Wonderful work!' : result.accuracy >= 75 ? 'Look how far you’ve come!' : 'A good step forward.';
  const copy = remaining ? 'Some words need a little more time. Let’s help them stick.' : 'You’ve recalled every word. Take that confidence with you.';
  return `<section class="results paper-card"><div class="result-emblem" aria-hidden="true">${icon('trophy')}<span>✦</span></div><span class="eyebrow">${result.review ? 'REVIEW COMPLETE' : 'PRACTICE COMPLETE'}</span><h1 tabindex="-1">${title}</h1><p class="lead">${copy}</p><p class="result-title">${e(practice.title)}</p><div class="result-stats"><div>${icon('chart')}<strong>${result.accuracy}%</strong><span>Overall accuracy</span></div><div>${icon('target')}<strong>${result.correct} / ${result.total}</strong><span>Correct answers</span></div><div>${icon('book')}<strong>${remaining}</strong><span>Words to review</span></div></div><p class="small muted">Accuracy and correct answers cover your first four rounds.</p>${result.review ? `<p class="review-summary" role="status">Last review: ${result.review.correct} / ${result.review.total} recalled. ${remaining ? `${remaining} ${remaining === 1 ? 'word is' : 'words are'} still ready for another try.` : 'No words left to review.'}</p>` : ''}${remaining ? `<div class="review-words">${result.remaining.map(i => `<div><strong>${e(practice.items[i].term)}</strong><span>${e(practice.items[i].meaning)}</span></div>`).join('')}</div>` : '<p class="all-done">✓ All words recalled</p>'}<div class="actions centered"><button id="finish" class="button ${remaining ? 'secondary' : 'primary'}">Finish <span aria-hidden="true">✓</span></button>${remaining ? `<button id="review" class="button primary">Review ${remaining} ${remaining === 1 ? 'word' : 'words'} →</button>` : ''}</div><button class="text-button" id="replay">Play again</button></section>`;
}
