import { brand, escape as e } from './dom.js';
import { icon } from './icons.js';
import { getWorld } from '../worlds.js';

export function studioShell(page) {
  const nav = [['dashboard', 'home', 'Dashboard'], ['create', 'plus', 'Create Practice'], ['library', 'library', 'My Library'], ['folders', 'folder', 'Folders'], ['backup', 'backup', 'Backup']];
  return `<div class="teacher-shell"><header class="studio-header" style="--studio-art:url('${getWorld('uk').art}')"><a class="brand" href="#dashboard" id="brand-home">${brand}</a><div><strong>Teacher Studio</strong><span>Learn English. Explore the World.</span></div><span class="private-badge">● Private workspace</span><button class="icon-button header-signout" data-sign-out aria-label="Sign out" title="Sign out">${icon('logout')}</button></header><aside class="sidebar"><div class="workspace-label">YOUR TEACHING SPACE</div><nav aria-label="Main navigation">${nav.map(([key, symbol, label]) => `<button data-nav="${key}" class="nav-item ${page === key ? 'active' : ''}" ${page === key ? 'aria-current="page"' : ''}>${icon(symbol)}${label}</button>`).join('')}</nav><div class="sidebar-note"><span aria-hidden="true">✦</span><p>Words open worlds.<br><b>You open the door.</b></p></div><div class="teacher-profile"><span class="avatar">R</span><div><b>Ralina</b><small>Teacher workspace</small></div><button data-sign-out class="icon-button" aria-label="Sign out" title="Sign out">${icon('logout')}</button></div></aside><div class="teacher-body"><main id="teacher-content" tabindex="-1"></main><footer>Made for your teaching. Ready for their next adventure. <span aria-hidden="true">✦</span></footer></div></div>`;
}

export function foldersView(library, compact = false) {
  const folders = compact ? library.folders.slice(0, 4) : library.folders;
  return folders.length ? `<div class="folder-grid">${folders.map(f => {
    const count = library.sets.filter(s => s.folderId === f.id).length;
    return `<article class="folder-tile">${icon('folder')}<div><h3><button class="text-button" data-open-folder="${e(f.id)}">${e(f.name)}</button></h3><p>${count} ${count === 1 ? 'practice' : 'practices'}</p></div>${compact ? '' : `<div class="folder-tile-actions"><button class="text-button" data-rename-folder="${e(f.id)}">Rename</button><button class="text-button danger" data-delete-folder="${e(f.id)}" ${count ? 'disabled title="Move the practices before deleting this folder"' : ''}>Delete empty folder</button></div>`}</article>`;
  }).join('')}</div>` : '<p class="folder-empty">Your folders will appear here. Give your next topic a home.</p>';
}

export function dashboardView(library, recentCards) {
  return `<div class="page-heading"><div><span class="eyebrow">YOUR NEXT LESSON STARTS HERE</span><h1>Welcome back, Ralina! <span class="inline-spark" aria-hidden="true">✦</span></h1><p>Create and organise vocabulary practice for your students.</p></div><button class="button primary" data-create>+ Create Practice</button></div><div class="summary-grid"><div>${icon('library', 'summary-icon violet')}<strong>${library.sets.length}</strong><span>Practices in your library</span></div><div>${icon('folder', 'summary-icon aqua')}<strong>${library.folders.length}</strong><span>Folders</span></div></div><section class="studio-panel"><div class="section-title"><h2>Recent Practices</h2><button id="view-library" class="text-button">View all practices →</button></div><div class="recent-practices">${recentCards}</div></section><section class="studio-panel"><div class="section-title"><h2>My Folders</h2><button id="view-folders" class="text-button">Manage folders →</button></div>${foldersView(library, true)}</section><section class="studio-panel"><div class="section-title"><h2>Quick Actions</h2></div><div class="quick-actions"><button data-create>${icon('plus')}<span>New Practice</span></button><button id="quick-folder">${icon('folder')}<span>Create Folder</span></button><button id="quick-backup">${icon('backup')}<span>Export Backup</span></button></div></section>`;
}

export function backupView(library) {
  return `<div class="page-heading"><div><span class="eyebrow">A COPY TO KEEP</span><h1>Backup</h1><p>Your library, safely in your own hands.</p></div></div><div class="backup-grid"><section class="panel backup-panel">${icon('backup')}<h2>Export your library</h2><p>Download a JSON file with your ${library.sets.length} practices and ${library.folders.length} folders. Keep it somewhere you can find again.</p><button class="button primary" id="backup">Export Backup</button></section><section class="panel backup-panel">${icon('library')}<h2>Import a backup</h2><p>Restore practices and folders as new private copies. Your current library stays in place. Share each imported practice when it’s ready.</p><button class="button secondary" id="import">Choose backup file</button><input type="file" id="import-file" accept="application/json,.json" hidden></section></div><p class="small muted">Backups are files you download and keep. Your browser does not save them automatically.</p>`;
}
